GET http://127.0.0.1:3000/task/all?title=ZZP HTTP/1.0
Content-Type: "application/json"

### 
POST http://127.0.0.1:3000/task HTTP/1.0
Content-Type: application/json

{  "id":999,
  "title": "ZZP万岁",
  "description": "想念的801啊，日子真难混",
  "status": "1"
}
###
GET http://127.0.0.1:3000/task/3 HTTP/1.0
Content-Type: "application/json"
authorization:"Basic base64-user-password"

###
DELETE  http://127.0.0.1:3000/task/5 HTTP/1.0
Content-Type: "application/json"

###
PATCH http://127.0.0.1:3000/task/update/5 HTTP/1.0
Content-Type: application/json

{  

  "title": "测试一下ZZp",
  "description": "落水无情，人有意",
  "status": "1"
}