@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlNWQ1Y2E4LWFkNzQtNDJkYy04Y2I5LWMxMDU4ODIxOTc4OSIsImlhdCI6MTY1MzgzOTgyNiwiZXhwIjoxNjUzODQzNDI2fQ.960FlcYYst36AXdYBTSZDUVihIgHp0fJdXNA1bNbZR8
GET http://127.0.0.1:3000/task/all HTTP/1.0
Content-Type: "application/json"
Authorization:{{token}}
###
GET http://127.0.0.1:3000/task/10 HTTP/1.0
Content-Type: "application/json"
Authorization:{{token}}
### 
POST http://127.0.0.1:3000/task HTTP/1.0
Content-Type: application/json
Authorization:{{token}}

{  "id":9199,
  "title": "ZZP万岁",
  "description": "想念的801啊，日子真难混",
  "status": "1"
}
###
GET http://127.0.0.1:3000/task/13 HTTP/1.0
Content-Type: "application/json"
Authorization:{{token}}

###
DELETE  http://127.0.0.1:3000/task/5 HTTP/1.0
Content-Type: "application/json"

###
PATCH http://127.0.0.1:3000/task/update/5 HTTP/1.0
Content-Type: application/json
Authorization:{{token}}

{  

  "title": "测试一下ZZp",
  "description": "落水无情，人有意",
  "status": "1"
}

### 注册
POST  http://127.0.0.1:3000/auth/register HTTP/1.0
Content-Type: application/json

{
  "username":"1234",
  "password":"12345678Ab@"
}

### 
### 获取用户列表
GET http://127.0.0.1:3000/auth HTTP/1.0
Content-Type: application/json
Authorization:{{token}}
### 登录
POST http://127.0.0.1:3000/auth/login HTTP/1.0
Content-Type: application/json

{
  "username":"ct2",
  "password":"12345678Ab@"
}